.\" Copyright (C) 2013 Jeremy Brubaker
.\"
.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH CBASERC 5 "JULY 2013" cbase-1.0 "User Manuals"
.SH NAME
cbaserc \- configuraqtion file for cbase
.SH SYNOPSIS
.B ${home}/.cbaserc
.SH DESCRIPTION
.B cbase
DESCRIBE IT
.SH OPTIONS
.IP OPTION
.SH AUTHOR
Written by Jeremy Brubaker.
.SH "SEE ALSO"
.BR cbase (1),
