.\" Copyright (C) 2011 Jeremy Brubaker
.\"
.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH CBASE 1 "JUNE 2011" cbase-1.0 "User Manuals"
.SH NAME
cbase \- create a C language project tree with some boilerplate code
.SH SYNOPSIS
.B cbase -n
.I project_name
[-vV]
.SH DESCRIPTION
.B cbase
DESCRIBE IT
.SH OPTIONS
.IP -n project_name
Name of project to create.
.IP "-v "
Turn on verbose output.
.IP -V
Print version info.
.SH FILES
.I ~/.cbaserc
.RS
Per user configuration file. See
.BR cbaserc (5)
for further details.
.SH BUGS
None yet. I haven't finished writing it.
.SH AUTHOR
Written by Jeremy Brubaker.
.SH "SEE ALSO"
.BR cbaserc (5),
